function [fname, params] = mdrnn_l2_filename(params)

params.usepcd = 0;
params.draw_sample = 0;
params.fname = sprintf('%s_%s_x_%d_z_%d_hx_%d_hz_%d_p_%d_ln_%d_img_%d_eps_%g_%g_l2r_%g_px_%g_pz_%g_%s_spp_%g_%g_sphx_%g_%g_sphz_%g_%g_nmf_%d_bs_%d_up_x_%d_z_%d_mom_%d', ...
    params.dataset, params.traintype, params.numvx, params.numvz, params.numhx, params.numhz, params.numpen, ...
    params.doc_length, params.imgperbatch, params.eps, params.eps_decay, params.l2reg, params.px, params.pz, ...
    params.sp_type, params.sp_target_p, params.sp_reg_p, params.sp_target_hx, params.sp_reg_hx, ...
    params.sp_target_hz, params.sp_reg_hz, params.nmf, ...
    params.batchsize, params.upfactor_x, params.upfactor_z, params.momentum_change);

fname = params.fname;
disp(fname);

return;
